### ISSUE TITLE
[Set] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by EunHee-Jeong** [SOPT-30th-Joint-Seminar-15/Client-iOS#1]
## 👻 TODO

- [x] Issue・Pull Request Template 넣기
- [x] Xcode Project 파일 생성
- [x] 폴더링, dummy 파일 추가
- [x] Color 에셋 및 Extension 추가
- [x] Then 라이브러리 설치
- [x] Merge 막기 (1명 이상 Approve)
